### ISSUE TITLE
repository structure

### ISSUE THREAD

**Issue by fedhere** [AbdulRehmanUDEL/DSPS_ARehman#1]
read the delivery instruction carefully: each week's homework needs its own folder. This week you need a folder HW2_zGermain, and the notebooks go inside that folder, with a README that describes what you did on your own and who you worked with

**Comment by AbdulRehmanUDEL** [comment]
Hi,
Sorry for the mistake. I am slowly picking up with GitHub.  I will make new folders for the homework next time. Thank you.
